// ============================================
// 🎯 Mock Data สำหรับทดสอบระบบ
// ============================================

import { MenuCategory, MenuItem, Table } from '@/types';

// 📌 หมวดหมู่อาหาร
export const mockCategories: MenuCategory[] = [
  {
    id: 'cat-1',
    name: 'อาหารจานหลัก',
    nameEn: 'Main Dishes',
    icon: 'UtensilsCrossed',
    order: 1,
    isActive: true,
  },
  {
    id: 'cat-2',
    name: 'ของทอด',
    nameEn: 'Fried',
    icon: 'Flame',
    order: 2,
    isActive: true,
  },
  {
    id: 'cat-3',
    name: 'ของหวาน',
    nameEn: 'Desserts',
    icon: 'IceCream',
    order: 3,
    isActive: true,
  },
  {
    id: 'cat-4',
    name: 'เครื่องดื่ม',
    nameEn: 'Beverages',
    icon: 'Coffee',
    order: 4,
    isActive: true,
  },
  {
    id: 'cat-5',
    name: 'ของว่าง',
    nameEn: 'Snacks',
    icon: 'Cookie',
    order: 5,
    isActive: true,
  },
];

// 📌 รายการอาหาร
export const mockMenuItems: MenuItem[] = [
  // อาหารจานหลัก
  {
    id: 'menu-1',
    name: 'ข้าวผัดกุ้ง',
    nameEn: 'Shrimp Fried Rice',
    description: 'ข้าวผัดกุ้งสดใหม่ ปรุงรสชาติกลมกล่อม',
    categoryId: 'cat-1',
    price: 60,
    imageUrl: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=400',
    isAvailable: true,
    isRecommended: true,
    preparationTime: 15,
    tags: ['popular', 'seafood'],
  },
  {
    id: 'menu-2',
    name: 'ผัดไทยกุ้งสด',
    nameEn: 'Pad Thai with Shrimp',
    description: 'ผัดไทยรสเด็ด กุ้งสดใหญ่',
    categoryId: 'cat-1',
    price: 70,
    imageUrl: 'https://images.unsplash.com/photo-1559314809-0d155014e29e?w=400',
    isAvailable: true,
    isRecommended: true,
    preparationTime: 12,
    tags: ['signature', 'seafood'],
  },
  {
    id: 'menu-3',
    name: 'ต้มยำกุ้ง',
    nameEn: 'Tom Yum Kung',
    description: 'ต้มยำกุ้งน้ำข้น รสจัดจ้าน',
    categoryId: 'cat-1',
    price: 80,
    imageUrl: 'https://images.unsplash.com/photo-1548943487-a2e4e43b4853?w=400',
    isAvailable: true,
    isRecommended: true,
    preparationTime: 20,
    tags: ['spicy', 'soup'],
  },
  {
    id: 'menu-4',
    name: 'ข้าวผัดหมู',
    nameEn: 'Pork Fried Rice',
    description: 'ข้าวผัดหมูสูตรต้นตำรับ',
    categoryId: 'cat-1',
    price: 50,
    imageUrl: 'https://images.unsplash.com/photo-1516684732162-798a0062be99?w=400',
    isAvailable: true,
    preparationTime: 10,
  },
  
  // ของทอด
  {
    id: 'menu-5',
    name: 'ไก่ทอดหาดใหญ่',
    nameEn: 'Hatyai Fried Chicken',
    description: 'ไก่ทอดกรอบนอกนุ่มใน',
    categoryId: 'cat-2',
    price: 45,
    imageUrl: 'https://images.unsplash.com/photo-1562967914-608f82629710?w=400',
    isAvailable: true,
    isRecommended: true,
    preparationTime: 15,
    tags: ['crispy', 'popular'],
  },
  {
    id: 'menu-6',
    name: 'ปีกไก่ทอด (5 ชิ้น)',
    nameEn: 'Fried Chicken Wings',
    description: 'ปีกไก่ทอดซอสเผ็ด',
    categoryId: 'cat-2',
    price: 55,
    imageUrl: 'https://images.unsplash.com/photo-1608039755401-742074f0548d?w=400',
    isAvailable: true,
    preparationTime: 12,
  },
  
  // ของหวาน
  {
    id: 'menu-7',
    name: 'ข้าวเหนียวมะม่วง',
    nameEn: 'Mango Sticky Rice',
    description: 'ข้าวเหนียวมะม่วงน้ำดอกไม้หอมหวาน',
    categoryId: 'cat-3',
    price: 50,
    imageUrl: 'https://images.unsplash.com/photo-1541172132-c0e897544ff8?w=400',
    isAvailable: true,
    isRecommended: true,
    preparationTime: 5,
    tags: ['sweet', 'traditional'],
  },
  {
    id: 'menu-8',
    name: 'บัวลอย',
    nameEn: 'Rice Balls in Coconut Milk',
    description: 'บัวลอยสามสี กะทิหอมหวาน',
    categoryId: 'cat-3',
    price: 35,
    imageUrl: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=400',
    isAvailable: true,
    preparationTime: 5,
  },
  
  // เครื่องดื่ม
  {
    id: 'menu-9',
    name: 'ชาเย็น',
    nameEn: 'Thai Iced Tea',
    description: 'ชาเย็นต้นตำรับ',
    categoryId: 'cat-4',
    price: 25,
    imageUrl: 'https://images.unsplash.com/photo-1587080266227-677cc2a4e76e?w=400',
    isAvailable: true,
    preparationTime: 3,
  },
  {
    id: 'menu-10',
    name: 'น้ำมะนาว',
    nameEn: 'Lime Juice',
    description: 'น้ำมะนาวสดเย็นชื่นใจ',
    categoryId: 'cat-4',
    price: 20,
    imageUrl: 'https://images.unsplash.com/photo-1523677011781-c91d1bbe2f0e?w=400',
    isAvailable: true,
    preparationTime: 3,
  },
  {
    id: 'menu-11',
    name: 'โค้ก',
    nameEn: 'Coke',
    categoryId: 'cat-4',
    price: 15,
    isAvailable: true,
    preparationTime: 1,
  },
  // ของว่าง
  {
    id: 'menu-12',
    name: 'ปอเปี๊ยะทอด',
    nameEn: 'Fried Spring Rolls',
    description: 'ปอเปี๊ยะทอดกรอบอร่อย พร้อมน้ำจิ้ม',
    categoryId: 'cat-5',
    price: 40,
    imageUrl: 'https://images.unsplash.com/photo-1541172132-c0e897544ff8?w=400',
    isAvailable: true,
    isRecommended: true,
    preparationTime: 8,
  },
  {
    id: 'menu-13',
    name: 'ทอดมันกุ้ง',
    nameEn: 'Shrimp Cake',
    description: 'ทอดมันกุ้งสูตรพิเศษ กรอบนอกนุ่มใน',
    categoryId: 'cat-5',
    price: 60,
    imageUrl: 'https://images.unsplash.com/photo-1559847844-5315695dadae?w=400',
    isAvailable: true,
    preparationTime: 10,
  },
  {
    id: 'menu-14',
    name: 'เฟรนช์ฟรายส์',
    nameEn: 'French Fries',
    description: 'มันฝรั่งทอดกรอบ เสิร์ฟร้อนๆ',
    categoryId: 'cat-5',
    price: 35,
    imageUrl: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=400',
    isAvailable: true,
    preparationTime: 5,
  },
];

// 📌 โต๊ะอาหาร
export const mockTables: Table[] = [
  {
    id: 'table-1',
    tableNumber: '1',
    status: 'open',
    qrCode: 'QR-TABLE-1',
    capacity: 4,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'table-2',
    tableNumber: '2',
    status: 'open',
    qrCode: 'QR-TABLE-2',
    capacity: 4,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'table-3',
    tableNumber: '3',
    status: 'open',
    qrCode: 'QR-TABLE-3',
    capacity: 6,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'table-4',
    tableNumber: '4',
    status: 'open',
    qrCode: 'QR-TABLE-4',
    capacity: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'table-5',
    tableNumber: '5',
    status: 'open',
    qrCode: 'QR-TABLE-5',
    capacity: 8,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
